# Generated by Django 6.1 on 2026-09-14 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('competition', 'Competition'), ('certification', 'Certification'), ('award', 'Award'), ('publication', 'Publication'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='other', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('achieved_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
