# Generated by Django 6.1 on 2026-09-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
    ]
